### ISSUE TITLE
crash in add a card

### ISSUE THREAD

**Issue by roumano** [jtbgroup/kodi-search-card#10]
If i enable the kodi-serch-card,

it's failed to load the card to automatic add it.

![crash kodi search card](https://user-images.githubusercontent.com/6402894/154032995-f3b29e89-a1f8-45cd-97a2-6211ae90222a.png)
 

Same behavior with these version : 
- 2.7.1_b
- 2.7.0_b
- 2.6.2
- 2.6.1_b
- master

If i remove the kodi-search-card, i don't see this spin turn forever, so it's how i fount it this card the issue.

PS : no error found on my home assistant log

**Comment by jtbgroup** [comment]
Bonjour Roumano! 😄 

Indeed I didn't notice it wasn't available anymore. I'll check ASAP. For the time being, you can add the card manually I think.

**Comment by jtbgroup** [comment]
should work with the 2.7.2_b

**Comment by roumano** [comment]
Yes it's work as expected ! 
Thanks for the reactivity ..
