### ISSUE TITLE
hard to add a specific title name from a computer

### ISSUE THREAD

**Issue by roumano** [jtbgroup/kodi-search-card#11]
Specially on big screen, it's not easy to add (or play) a song

don't have the issue to play a disc or a artist.

To play (or Add) need to click on the right , but it's not so simple as it's at 1200px far of the title name
and the result got ~40 result 
![kodi-search-card_hard_align](https://user-images.githubusercontent.com/6402894/160083170-78f65a1e-1d0f-49d3-9f87-6ab461617351.png)

Not sure what it's the best about IHMO but a idea is be able to click on the title of the song

PS : sorry for the title of the bug, i don't found something better but feel free to rename it

**Comment by jtbgroup** [comment]
Hello,

I'm on it. I just pushed a version on the Dev branch but still need to test it. The title and the track number will be displayed in bold when you pass the mouse over the action button.

**Comment by jtbgroup** [comment]
Hi Roumano,

the beta version is available via hacs. Let me know if it suits your needs.

**Comment by jtbgroup** [comment]
version 2.8.0 is out
