### ISSUE TITLE
Show videos too

### ISSUE THREAD

**Issue by Rudd-O** [jtbgroup/kodi-search-card#16]
### Description

I have a large collection of songs in video.  These do not show up in search results, and the media order type does not appear to list these.  I would like to see them in search.  Thanks.

### Proposition

Show videos in search results.

**Comment by jtbgroup** [comment]
Hi,

I never used Music Video; that's why it's not implemented. I tried to add one in my library (an .mkv) but it doesn't seem to work why my file. Can you give me an advise about where to find some file for testing?

Regards,

Gautier

**Comment by Rudd-O** [comment]
Sure, would love to help!  Download any WebM from [here](https://www.webmfiles.org/demo-files/), add to a folder in your Kodi device, then in the source configuration for music videos add that folder, then rescan.  You should now be able to go to Music -> Videos, and it should be listed there.

**Comment by jtbgroup** [comment]
Added in version 3.3
