### ISSUE TITLE
How can I hide Recently played?

### ISSUE THREAD

**Issue by Stooovie** [jtbgroup/kodi-search-card#17]
How can I hide the Recently played button? It doesn't do anything on my setup and I don't see it in the documentation. Thank you!

KSS 3.3.0 on HA 2022.9.2

**Comment by jtbgroup** [comment]
Hi,

There was no option and to be honest, I forgot this part when reviewing the layout of the card. Now fixed with version 3.4.0. Can you confirm it works as expected?

**Comment by Stooovie** [comment]
It works, the layout is a bit weird but fine and working, thanks!
![Screen Shot 2022-09-13 at 23 39 01](https://user-images.githubusercontent.com/10572373/190014136-fd45d8e4-0505-4bcd-85dc-29bb257dc298.jpg)

**Comment by jtbgroup** [comment]
Hi,
I know the layout isn't really good. I wanted to solve it quick but I'm not proud of the design :-)
If you have an idea for a better one, don't hesitate!

**Comment by Stooovie** [comment]
I think the previous one with three rows (1 search field, 2 search and clear, 3 recently added) was fine :)

**Comment by jtbgroup** [comment]
The thing is that I have 2 other controls: recently played and the action mode. And grouping the 'recent' controls make sense when you display everything.

**Comment by jtbgroup** [comment]
Hi, just published a 3.4.2 beta with a better layout. You can try it.
