### ISSUE TITLE
Cannot enter text into search box on iOS home assistant app

### ISSUE THREAD

**Issue by sebirdman** [jtbgroup/kodi-search-card#2]
Every time i try to type into the textbox, my keyboard comes up then immediately goes back down. No matter where i put the card it seems to do this.

**Comment by jtbgroup** [comment]
Hi,

I indeed have the same problem on android (and even via the browser). As I mostly had enough time to type, I didn't focus on that bug.

I now checked it as I understand it might be annoying. Beta version is available on branch [develop](https://github.com/jtbgroup/kodi-search-card/tree/develop). I still need a few days to test it, but you already can try it. Be aware you also need the beta version (also on branch develop) of the Integration 'Kodi Media Sensor'

**Comment by jtbgroup** [comment]
Hello,

Did you tried the last version? Did it solve the problem?

**Comment by Stooovie** [comment]
It did for me. I have no issues searching and playing media from the Kodi Search card beta on iOS 15 and HA 2021.10.1.

**Comment by jtbgroup** [comment]
ok, I close this issue.
