### ISSUE TITLE
"All recently added" not working

### ISSUE THREAD

**Issue by Stooovie** [jtbgroup/kodi-search-card#3]
Pushing "All recently added" returns `Failed to call service kodi_media_sensors/call_method. The given media type is unsupported: recent`

Kodi Media Sensors is updated to 3.1.0_b and reinstalled as of now, all sensors are enabled. HA 2021.10.1.

**Comment by jtbgroup** [comment]
Hi, did you updated the Kodi Media Sensor integration to the beta version
too?

**Comment by Stooovie** [comment]
Yes I did. I have trouble with this and images not coming through from Kodi, so I'm trying different versions. It did not work with non-beta version as well.

**Comment by Stooovie** [comment]
[Here's my log](http://hastebin.com/cokozogecu
)

**Comment by Stooovie** [comment]
It started to work without any intervention 20 minutes later. Case closed. Images aren't coming through though, even with both HA and Kodi NOT using SSL.

**Comment by jtbgroup** [comment]
Hi, good to hear it was a cache problem. The images only work for me when
using Firefox on a computer; the android app or Chrome on a computer do not
show the images. I call HA through a proxy for ssl and Kodi is only http
which I suppose causes the conflict for Chrome.

**Comment by Stooovie** [comment]
Interesting that the Upcoming media cards have no such issues, images from the same Kodi entity show just fine.

**Comment by jtbgroup** [comment]
I'll check the difference. Thanks for the hint. 👍. I know the this sensor
changes a little bit the URL of the picture received from Kodi. Maybe I can
get the image from HA media player instead of Kodi directly.

**Comment by Stooovie** [comment]
If I may, here's a feature suggestion: include TV episodes in "All recently added". Until Upcoming media cards support playing of media by tapping their panels, this would be the next best thing.

**Comment by jtbgroup** [comment]
Strange. I thought the search on recently added items included the episodes
of the TV shows. I'll check next week.

Indeed the upcoming media card doesn't allow to play directly a media item;
this was a main reason for developing a new one.

**Comment by Stooovie** [comment]
Both TV shows in All Recently Added and thumbnails work in the latest betas, awesome!

**Comment by Stooovie** [comment]
But there's a new problem, any search returns:

Failed to call service
kodi_media_sensors/call_method
'KodiSearchEntity' object has no attribute
"format_songs

And doesn't actually work.

**Comment by jtbgroup** [comment]
Did you update the integration and reboot too?

**Comment by jtbgroup** [comment]
Sorry, this comes from the code... a stupid bug... as usual.
Thanks for reporting. New beta version available of the integrator.

**Comment by Stooovie** [comment]
It's working fine now, everything seems to work. There's a little cosmetic issue but maybe that's on my end - the thumbnails have a bit of Grey overlay, look: 
![image](https://user-images.githubusercontent.com/10572373/136740427-d8b11113-1043-4239-9a36-d0cfad1f63d4.png)

But I don't really mind that. Thanks for the great work!

**Comment by jtbgroup** [comment]
You're right. I did that to have at least a light grey square i case of no cover (for songs). So the user sees where to click. I use the same UI trick in the playlist : overlay for all the playlist items except the currently playing item. Not sure this is the best way to do it...

I keep that in mind for a future release. :-)

**Comment by jtbgroup** [comment]
did you try the last version? Overlays are used in another way now.

**Comment by Stooovie** [comment]
> did you try the last version? Overlays are used in another way now.

Yes! The card is working great now. Newly added episodes aren't showing thumbnails (only the default grey icon with the clapperboard) but I'm not sure when that started. Movies display and work flawlessly.

EDIT: the Upcoming Media and Recently Added Kodi cards do show images.

**Comment by Stooovie** [comment]
Please disregard my previous comment. It was probably some kind of fluke, the card is flawless now, up-to-date, with thumbnails and playback.

**Comment by jtbgroup** [comment]
I close this item as it seems ok now.
Thanks for all your feedback!
