### ISSUE TITLE
Episode playback doesn't start

### ISSUE THREAD

**Issue by Stooovie** [jtbgroup/kodi-search-card#4]
I can search just fine, I'm getting thumbnails, I can play movies from the search results, but when I search for a series, I can't start playback of an episode from the search results. That only works for movies. I can, however, start playback of a season by tapping its thumbnail. But playing a particular episode is not possible. Search card 2.2.0 on HA 2021.11.5. Please look into it, thanks!

**Comment by jtbgroup** [comment]
Hello,

Did you install the last beta version? I suppose you mean playing an episode from the 'TVShow Season Details' section? 
If yes, indeed, I have the same problem. I check it.

For the time being, as workaround, you should be able to search the episode with the title and play it.

**Comment by jtbgroup** [comment]
Just pushed a beta version (2.3.1_b). Hope it helps.

**Comment by Stooovie** [comment]
Perfect, it's working! Thanks!

**Comment by jtbgroup** [comment]
Great! Thank you for the report.
I'll use those beta version for a couple of days before pushing it in 'production'.
I will close the bug at this moment.

**Comment by jtbgroup** [comment]
the new version is now in production.
If there is something wrong, you know the way ;-)
