### ISSUE TITLE
Suggestion: have "all recent" always displayed 

### ISSUE THREAD

**Issue by Stooovie** [jtbgroup/kodi-search-card#5]
I love your Search card. Here's a feature suggestion: an option to have the "all recently added" media always displayed (so, not only after pushing the button). This way I could do away with the Kodi Recent cards that do not offer tap to playback functionality.

**Comment by jtbgroup** [comment]
:laughing:
Well... that's not a so easy one!!!!!

I would have to review the code as I should use a polling mechanism and an option to keep the result instead of purging it. 
This would be an option on the integration, not on the card.

I can't promise to check this soon, but I keep it in mind.

**Comment by jtbgroup** [comment]
Ok, just published a new version of the integration (3.3.0_b) in pre-release. You can try (using hacs).
There is a new option in the config of the integration for the 'keep alive timer'. when set to 0, the search will be performed after every poll of the sensor. 

Let me know if this is what you need ;-)

**Comment by Stooovie** [comment]
Hi, that's looking good! Boy you're fast :) Thanks!
