### ISSUE TITLE
Search : let the user choose where he / she adds the item in the playlist. Currently at the first position.  Could also be another button on the card

### ISSUE THREAD

**Issue by jtbgroup** [jtbgroup/kodi-search-card#6]

**Comment by roumano** [comment]
Will be nice to have, actually can "only" possible to play, it's not possible to add to the queue...

**Comment by jtbgroup** [comment]
New version 2.6.0_b in beta. You can upgrade with HACS.
Documentation here: https://github.com/jtbgroup/kodi-search-card/tree/develop

**Comment by roumano** [comment]
Tested and work like a charm ! 
I love this feature, BIG thanks !

So i think we can close the issue, isn't it ?

**Comment by jtbgroup** [comment]
thanks for testing so quick!
I'll leave it open until I build the real release (estimated in 2 weeks).

**Comment by Stooovie** [comment]
Can we have a toggle for disabling this in Lovelace? I literally never need this and it looks suboptimal on my system:
![Screenshot 2022-01-24 at 22 29 03](https://user-images.githubusercontent.com/10572373/150868050-369bb22a-d5f5-4d21-b508-50e77eeae4ba.jpg)

**Comment by jtbgroup** [comment]
Hello Stoovie,

I also noticed the bad layout on my phone yesterday. This is something I have to change probably before the final release of this functionality. 

Great idea to add a property in the config. It's done in the 2.6.1_b (beta release). Just check it.

@roumano : this new property is set to false by default, meaning you don't see the Action Mode Component. I did that to have to have a smooth transition between the versions. Please add 'show_action_mode : true' in your config to display the component.

**Comment by Stooovie** [comment]
You're unstoppable :) thanks!

**Comment by Stooovie** [comment]
I had just one more thing to make the card perfect for my use: an ability to display TV shows before Movies (so, Shows first). I update and check these more often and it would be handy. Thank you!

**Comment by jtbgroup** [comment]
> You're unstoppable :) thanks!

I'll be off for a couple of days; I wanted to have it done :smile:

**Comment by jtbgroup** [comment]
> perfect for my use: an ability to display TV shows before Movies (so, Shows first). I update and check these more often and it would be handy. Thank you!

Ok. This is a new feature. Can you create a new issue for that please? 
Promised, I will not implement it before 2 weeks!

**Comment by jtbgroup** [comment]
the 'action method' is now available in the latest release
