### ISSUE TITLE
[feature request] Show TV shows first, Movies second

### ISSUE THREAD

**Issue by Stooovie** [jtbgroup/kodi-search-card#8]
Hi, I would love an ability to display TV shows before Movies (so, Shows first). I update and check these more often and it would be handy. Thank you!

**Comment by jtbgroup** [comment]
Hi Stoovie, the feature is implemented and available in beta, but you need to change the config of the card manually (parameter 'Order')
https://github.com/jtbgroup/kodi-search-card/tree/develop

**Comment by Stooovie** [comment]
That's so cool! Working as expected. Thank you!

**Comment by jtbgroup** [comment]
Request closed as runs now in production.
