### ISSUE TITLE
cant play episode

### ISSUE THREAD

**Issue by Stephan296** [jtbgroup/kodi-search-card#9]
When i search at a serie and i want to play an episode i get the next error in developer mode in Google Chrome:

TypeError: this.playEpisode is not a function.

There is also nothing happend on my tv.

**Comment by jtbgroup** [comment]
ok, I have a bug in the "Season details".  Is that what you use?
As temporary workaround you can search the episode by name and in the main resultset, you can click the episode to add or play it.

**Comment by jtbgroup** [comment]
Hi,
I changed the code. You can try it in beta using hacs. Don't forget to update the integration too as the bug was there... :smile:

**Comment by Stephan296** [comment]
Hi!

Works perfect! Maybe an option to also add serie info from kodi about the episode tot this view?
Regards!

**Comment by jtbgroup** [comment]
Hello,

There is not enough space for adding info in my opinion, but you can try to make a schema if you want. If you have an idea, don't hesitate and open a new issue.

**Comment by jtbgroup** [comment]
I close this bug, and wait for your new issue regarding your request.
